apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-mainsite

resources:
  - namespace.yaml
  - external-secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: redis-mainsite
  app.kubernetes.io/component: redis-cache
