apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr-mainsite-staging

resources:
  - ../../base/solr-mainsite-staging
  - custom-ingress.yaml

commonLabels:
  environment: staging
