---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr-mainsite-prod
  namespace: solr-mainsite
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mainsite.libsolr.lib.utk.edu
    secretName: solr-mainsite-prod-tls
  rules:
  - host: mainsite.libsolr.lib.utk.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solr-mainsite-solrcloud-common
            port:
              number: 8983
