apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr-mainsite

resources:
  - ../../base/solr-mainsite
  - custom-ingress.yaml

commonLabels:
  environment: production

patches:
  - patch: |-
      - op: replace
        path: /spec/dataStorage/persistent/reclaimPolicy
        value: Retain
    target:
      kind: SolrCloud
      name: solr-mainsite
