apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring-namespace.yaml
  - flux-rbac.yaml
  - kube-prometheus-stack.yaml

commonLabels:
  app.kubernetes.io/part-of: kube-prometheus-stack
